import type { BiomeData } from "./type";

export const BIOME_DATA: Array<BiomeData> = [
  {
    biomeId: "minecraft:deep_lukewarm_ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "lukewarm", "deep"],
    generate: 220,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:ice_mountains",
    temperature: 0,
    rainfall: 0.5,
    dimension: "overworld",
    category: "mountain",
    tags: ["frozen", "ice", "mountain"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:swampland",
    temperature: 0.8,
    rainfall: 0.5,
    dimension: "overworld",
    category: "swamp",
    tags: ["swamp"],
    generate: 124,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:warm_ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "warm"],
    generate: 183,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:frozen_river",
    temperature: 0,
    rainfall: 0.5,
    dimension: "overworld",
    category: "river",
    tags: ["river", "frozen"],
    generate: 69,
    snowAccumulation: [0.125, 0.25],
  },
  {
    biomeId: "minecraft:extreme_hills_edge",
    temperature: 0.6,
    rainfall: 0.6,
    dimension: "overworld",
    category: "mountain",
    tags: ["edge", "extreme_hills", "mountain"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:desert",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["desert"],
    generate: 205,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:extreme_hills",
    temperature: 0.2,
    rainfall: 0.3,
    dimension: "overworld",
    category: "mountain",
    tags: ["extreme_hills"],
    generate: 29,
    snowAccumulation: [0, 0.25],
  },
  {
    biomeId: "minecraft:forest",
    temperature: 0.7,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest"],
    generate: 1182,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:the_end",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "the_end",
    category: "the_end",
    tags: [],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:hell",
    temperature: 2,
    rainfall: 0,
    dimension: "nether",
    category: "nether",
    tags: [],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:plains",
    temperature: 0.8,
    rainfall: 0.4,
    dimension: "overworld",
    category: "plain",
    tags: ["plains", "bee_habitat"],
    generate: 1003,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:beach",
    temperature: 0.8,
    rainfall: 0.4,
    dimension: "overworld",
    category: "ocean",
    tags: ["beach", "warm"],
    generate: 223,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:jungle",
    temperature: 0.95,
    rainfall: 0.9,
    dimension: "overworld",
    category: "forest",
    tags: ["jungle", "rare"],
    generate: 193,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:cold_beach",
    temperature: 0.05,
    rainfall: 0.3,
    dimension: "overworld",
    category: "ocean",
    tags: ["beach", "cold"],
    generate: 28,
    snowAccumulation: [0.125, 0.25],
  },
  {
    biomeId: "minecraft:jungle_edge",
    temperature: 0.95,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["jungle", "edge"],
    generate: 133,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:stone_beach",
    temperature: 0.2,
    rainfall: 0.3,
    dimension: "overworld",
    category: "ocean",
    tags: ["beach", "store"],
    generate: 120,
    snowAccumulation: [0, 0.25],
  },
  {
    biomeId: "minecraft:cold_ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "cold"],
    generate: 429,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:savanna",
    temperature: 1.2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["savanna"],
    generate: 363,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:birch_forest",
    temperature: 0.6,
    rainfall: 0.6,
    dimension: "overworld",
    category: "forest",
    tags: ["birch", "forest", "bee_habitat"],
    generate: 212,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:birch_forest_hills",
    temperature: 0.6,
    rainfall: 0.6,
    dimension: "overworld",
    category: "forest",
    tags: ["birch", "forest", "hills", "bee_habitat"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:cold_taiga",
    temperature: -0.5,
    rainfall: 0.4,
    dimension: "overworld",
    category: "forest",
    tags: ["cold", "forest", "taiga"],
    generate: 203,
    snowAccumulation: [0.125, 0.5],
  },
  {
    biomeId: "minecraft:mega_taiga",
    temperature: 0.3,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest", "mega", "rare", "taiga"],
    generate: 60,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:mega_taiga_hills",
    temperature: 0.5,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest", "mega", "mega", "taiga"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:extreme_hills_plus_trees",
    temperature: 0.2,
    rainfall: 0.3,
    dimension: "overworld",
    category: "forest",
    tags: ["extreme_hills", "forest", "mountain"],
    generate: 21,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:jungle_hills",
    temperature: 0.95,
    rainfall: 0.9,
    dimension: "overworld",
    category: "forest",
    tags: ["jungle", "hills"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:savanna_plateau",
    temperature: 1,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["savanna", "plateau"],
    generate: 38,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:bamboo_jungle",
    temperature: 0.95,
    rainfall: 0.9,
    dimension: "overworld",
    category: "forest",
    tags: ["bamboo", "jungle"],
    generate: 56,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:bamboo_jungle_hills",
    temperature: 0.95,
    rainfall: 0.9,
    dimension: "overworld",
    category: "forest",
    tags: ["bamboo", "jungle", "hills"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:mesa_plateau",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["mesa", "plateau"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:taiga_hills",
    temperature: 0.25,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["taiga", "hills", "forest"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:frozen_ocean",
    temperature: 0,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "frozen"],
    generate: 198,
    snowAccumulation: [0.125, 0.25],
  },
  {
    biomeId: "minecraft:ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean"],
    generate: 673,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:mushroom_island",
    temperature: 0.9,
    rainfall: 1,
    dimension: "overworld",
    category: "ocean",
    tags: ["mushroom_island"],
    generate: 11,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:ice_plains",
    temperature: 0,
    rainfall: 0.5,
    dimension: "overworld",
    category: "plain",
    tags: ["frozen", "ice", "ice_plains"],
    generate: 238,
    snowAccumulation: [0.25, 1],
  },
  {
    biomeId: "minecraft:taiga",
    temperature: 0.25,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["taiga", "forest"],
    generate: 312,
    snowAccumulation: [0, 0.25],
  },
  {
    biomeId: "minecraft:desert_mutated",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["desert"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:extreme_hills_mutated",
    temperature: 0.2,
    rainfall: 0.3,
    dimension: "overworld",
    category: "drought",
    tags: ["extreme_hills", "mountain"],
    generate: 9,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:taiga_mutated",
    temperature: 0.25,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest", "taiga"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:swampland_mutated",
    temperature: 0.8,
    rainfall: 0.9,
    dimension: "overworld",
    category: "swamp",
    tags: ["swamp"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:jungle_edge_mutated",
    temperature: 0.95,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["jungle", "edge"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:roofed_forest_mutated",
    temperature: 0.7,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest", "roofed"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:legacy_frozen_ocean",
    temperature: 0,
    rainfall: 0,
    dimension: "overworld",
    category: "ocean",
    tags: ["frozen", "ocean"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:river",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "river",
    tags: ["river"],
    generate: 556,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:roofed_forest",
    temperature: 0.7,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest"],
    generate: 181,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:mesa",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["mesa"],
    generate: 76,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:desert_hills",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["desert", "hills"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:extreme_hills_plus_trees_mutated",
    temperature: 0.6,
    rainfall: 0.6,
    dimension: "overworld",
    category: "mountain",
    tags: ["extreme_hills", "forest", "mountain", "mutated"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:savanna_mutated",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["savanna", "mutated"],
    generate: 22,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:savanna_plateau_mutated",
    temperature: 1,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["savanna", "plateau", "mutated"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:meadow",
    temperature: 0.3,
    rainfall: 0.8,
    dimension: "overworld",
    category: "plain",
    tags: ["mountain", "meadow", "bee_habitat"],
    generate: 115,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:dripstone_caves",
    temperature: 0.2,
    rainfall: 0,
    dimension: "overworld",
    category: "cave",
    tags: ["caves", "dripstone_caves"],
    generate: 567,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:lush_caves",
    temperature: 0.9,
    rainfall: 0,
    dimension: "overworld",
    category: "cave",
    tags: ["caves", "lush_caves"],
    generate: 121,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:stony_peaks",
    temperature: 1,
    rainfall: 0.3,
    dimension: "overworld",
    category: "mountain",
    tags: ["mountain"],
    generate: 13,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:snowy_slopes",
    temperature: -0.3,
    rainfall: 0.9,
    dimension: "overworld",
    category: "mountain",
    tags: ["mountain", "frozen", "frozen_peaks"],
    generate: 41,
    snowAccumulation: [0.125, 0.5],
  },
  {
    biomeId: "minecraft:frozen_peaks",
    temperature: -0.7,
    rainfall: 0.9,
    dimension: "overworld",
    category: "mountain",
    tags: ["mountain", "frozen", "frozen_peaks"],
    generate: 18,
    snowAccumulation: [0.125, 0.25],
  },
  {
    biomeId: "minecraft:soulsand_valley",
    temperature: 2,
    rainfall: 0,
    dimension: "nether",
    category: "nether",
    tags: ["nether", "soulsand_valley"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:crimson_forest",
    temperature: 2,
    rainfall: 0,
    dimension: "nether",
    category: "nether",
    tags: ["netherwart_forest", "crimson_forest"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:warped_forest",
    temperature: 2,
    rainfall: 0,
    dimension: "nether",
    category: "nether",
    tags: ["netherwart_forest", "warped_forest"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:flower_forest",
    temperature: 0.7,
    rainfall: 0.8,
    dimension: "overworld",
    category: "nether",
    tags: ["flower_forest", "bee_habitat"],
    generate: 55,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:basalt_deltas",
    temperature: 2,
    rainfall: 0,
    dimension: "nether",
    category: "nether",
    tags: ["basalt_deltas"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:deep_ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "deep"],
    generate: 351,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:deep_warm_ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "warm", "deep"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:lukewarm_ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "lukewarm"],
    generate: 421,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:deep_cold_ocean",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "cold", "deep"],
    generate: 226,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:deep_frozen_ocean",
    temperature: 0,
    rainfall: 0.5,
    dimension: "overworld",
    category: "ocean",
    tags: ["ocean", "frozen", "deep"],
    generate: 99,
    snowAccumulation: [0.125, 0.25],
  },
  {
    biomeId: "minecraft:mushroom_island_shore",
    temperature: 0.9,
    rainfall: 1,
    dimension: "overworld",
    category: "ocean",
    tags: ["mushroom_island", "shore"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:forest_hills",
    temperature: 0.6,
    rainfall: 0.6,
    dimension: "overworld",
    category: "mountain",
    tags: ["hills", "forest", "bee_habitat"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:cold_taiga_hills",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "forest",
    tags: ["cold", "forest", "hills", "taiga"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:ice_plains_spikes",
    temperature: 0,
    rainfall: 1,
    dimension: "overworld",
    category: "plain",
    tags: ["frozen", "ice_plains"],
    generate: 17,
    snowAccumulation: [0.5, 1.5],
  },
  {
    biomeId: "minecraft:mesa_plateau_stone",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["mesa", "plateau", "rare", "stone"],
    generate: 53,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:sunflower_plains",
    temperature: 0.8,
    rainfall: 0.4,
    dimension: "overworld",
    category: "plain",
    tags: ["plains", "bee_habitat"],
    generate: 58,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:jungle_mutated",
    temperature: 0.95,
    rainfall: 0.9,
    dimension: "overworld",
    category: "forest",
    tags: ["jungle", "rare"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:birch_forest_mutated",
    temperature: 0.6,
    rainfall: 0.6,
    dimension: "overworld",
    category: "forest",
    tags: ["birch", "forest", "bee_habitat"],
    generate: 200,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:cold_taiga_mutated",
    temperature: 0.5,
    rainfall: 0.5,
    dimension: "overworld",
    category: "forest",
    tags: ["cold", "forest", "taiga"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:redwood_taiga_mutated",
    temperature: 0.25,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest", "mega", "mutated", "taiga"],
    generate: 57,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:redwood_taiga_hills_mutated",
    temperature: 0.7,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["forest", "hills", "mega", "mutated", "taiga"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:mesa_bryce",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["mesa", "mutated"],
    generate: 27,
    snowAccumulation: [0, 0.125],
  },
  {
    biomeId: "minecraft:mesa_plateau_stone_mutated",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["mesa", "plateau", "rare", "mutated", "stone"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:mesa_plateau_mutated",
    temperature: 2,
    rainfall: 0,
    dimension: "overworld",
    category: "drought",
    tags: ["mesa", "mutated", "plateau"],
    generate: null,
    snowAccumulation: null,
  },
  {
    biomeId: "minecraft:jagged_peaks",
    temperature: -0.7,
    rainfall: 0.9,
    dimension: "overworld",
    category: "mountain",
    tags: ["mountain", "frozen", "jagged_peaks"],
    generate: 19,
    snowAccumulation: [0.125, 0.25],
  },
  {
    biomeId: "minecraft:grove",
    temperature: -0.2,
    rainfall: 0.8,
    dimension: "overworld",
    category: "forest",
    tags: ["mountain", "cold", "grove"],
    generate: 81,
    snowAccumulation: [0.125, 0.25],
  },
  {
    biomeId: "minecraft:birch_forest_hills_mutated",
    temperature: 0.6,
    rainfall: 0.6,
    dimension: "overworld",
    category: "forest",
    tags: ["birch", "forest", "hills", "bee_habitat"],
    generate: null,
    snowAccumulation: null,
  },
];

export const BIOME_DIMENSION = ["overworld", "the_end", "nether"] as const;

export const BIOME_ID = [
  "minecraft:deep_lukewarm_ocean",
  "minecraft:ice_mountains",
  "minecraft:swampland",
  "minecraft:warm_ocean",
  "minecraft:frozen_river",
  "minecraft:extreme_hills_edge",
  "minecraft:desert",
  "minecraft:extreme_hills",
  "minecraft:forest",
  "minecraft:the_end",
  "minecraft:hell",
  "minecraft:plains",
  "minecraft:beach",
  "minecraft:jungle",
  "minecraft:cold_beach",
  "minecraft:jungle_edge",
  "minecraft:stone_beach",
  "minecraft:cold_ocean",
  "minecraft:savanna",
  "minecraft:birch_forest",
  "minecraft:birch_forest_hills",
  "minecraft:cold_taiga",
  "minecraft:mega_taiga",
  "minecraft:mega_taiga_hills",
  "minecraft:extreme_hills_plus_trees",
  "minecraft:jungle_hills",
  "minecraft:savanna_plateau",
  "minecraft:bamboo_jungle",
  "minecraft:bamboo_jungle_hills",
  "minecraft:mesa_plateau",
  "minecraft:taiga_hills",
  "minecraft:frozen_ocean",
  "minecraft:ocean",
  "minecraft:mushroom_island",
  "minecraft:ice_plains",
  "minecraft:taiga",
  "minecraft:desert_mutated",
  "minecraft:extreme_hills_mutated",
  "minecraft:taiga_mutated",
  "minecraft:swampland_mutated",
  "minecraft:jungle_edge_mutated",
  "minecraft:roofed_forest_mutated",
  "minecraft:legacy_frozen_ocean",
  "minecraft:river",
  "minecraft:roofed_forest",
  "minecraft:mesa",
  "minecraft:desert_hills",
  "minecraft:extreme_hills_plus_trees_mutated",
  "minecraft:savanna_mutated",
  "minecraft:savanna_plateau_mutated",
  "minecraft:meadow",
  "minecraft:dripstone_caves",
  "minecraft:lush_caves",
  "minecraft:stony_peaks",
  "minecraft:snowy_slopes",
  "minecraft:frozen_peaks",
  "minecraft:soulsand_valley",
  "minecraft:crimson_forest",
  "minecraft:warped_forest",
  "minecraft:flower_forest",
  "minecraft:basalt_deltas",
  "minecraft:deep_ocean",
  "minecraft:deep_warm_ocean",
  "minecraft:lukewarm_ocean",
  "minecraft:deep_cold_ocean",
  "minecraft:deep_frozen_ocean",
  "minecraft:mushroom_island_shore",
  "minecraft:forest_hills",
  "minecraft:cold_taiga_hills",
  "minecraft:ice_plains_spikes",
  "minecraft:mesa_plateau_stone",
  "minecraft:sunflower_plains",
  "minecraft:jungle_mutated",
  "minecraft:birch_forest_mutated",
  "minecraft:cold_taiga_mutated",
  "minecraft:redwood_taiga_mutated",
  "minecraft:redwood_taiga_hills_mutated",
  "minecraft:mesa_bryce",
  "minecraft:mesa_plateau_stone_mutated",
  "minecraft:mesa_plateau_mutated",
  "minecraft:jagged_peaks",
  "minecraft:grove",
  "minecraft:birch_forest_hills_mutated",
] as const;

export const BIOME_CATEGORY = [
  "ocean",
  "forest",
  "mountain",
  "drought",
  "cave",
  "swamp",
  "river",
  "plain",
  "nether",
  "the_end",
] as const;

export const BIOME_TAG = [
  "ocean",
  "deep",
  "river",
  "plains",
  "jungle",
  "forest",
  "birch",
  "taiga",
  "bamboo",
  "desert",
  "beach",
  "shore",
  "store",
  "savanna",
  "mesa",
  "plateau",
  "mountain",
  "stone",
  "hills",
  "jagged_peaks",
  "frozen_peaks",
  "extreme_hills",
  "edge",
  "swamp",
  "lukewarm",
  "warm",
  "cold",
  "frozen",
  "ice",
  "rare",
  "bee_habitat",
  "mega",
  "mushroom_island",
  "ice_plains",
  "roofed",
  "mutated",
  "meadow",
  "caves",
  "dripstone_caves",
  "lush_caves",
  "grove",
  "nether",
  "soulsand_valley",
  "netherwart_forest",
  "crimson_forest",
  "warped_forest",
  "flower_forest",
  "basalt_deltas",
] as const;
