export enum Quality {
  /** 普通 */
  COMMON = 1,
  /** 少见 */
  UNCOMMON = 2,
  /** 稀有 */
  RARE = 3,
  /** 史诗 */
  EPIC = 4,
  /** 传说 */
  LEGENDARY = 5,
  /** 位置 */
  UNKNOWN = 10,
}

/** 原版效果 */
export enum VanillaEffectId {
  /** 迅捷 */
  SPEED = "minecraft:speed",
  /** 缓慢 */
  SLOWNESS = "minecraft:slowness",
  /** 急迫 */
  HASTE = "minecraft:haste",
  /** 挖掘疲劳 */
  MINING_FATIGUE = "minecraft:mining_fatigue",
  /** 力量 */
  STRENGTH = "minecraft:strength",
  /** 瞬间治疗 */
  INSTANT_HEALTH = "minecraft:instant_health",
  /** 瞬间伤害 */
  INSTANT_DAMAGE = "minecraft:instant_damage",
  /** 跳跃升级 */
  JUMP_BOOST = "minecraft:jump_boost",
  /** 反胃 */
  NAUSEA = "minecraft:nausea",
  /** 生命恢复 */
  REGENERATION = "minecraft:regeneration",
  /** 抗性提升 */
  RESISTANCE = "minecraft:resistance",
  /** 抗火 */
  FIRE_RESISTANCE = "minecraft:fire_resistance",
  /** 水下呼吸 */
  WATER_BREATHING = "minecraft:water_breathing",
  /** 隐身 */
  INVISIBILITY = "minecraft:invisibility",
  /** 失明 */
  BLINDNESS = "minecraft:blindness",
  /** 夜视 */
  NIGHT_VISION = "minecraft:night_vision",
  /** 饥饿 */
  HUNGER = "minecraft:hunger",
  /** 虚弱 */
  WEAKNESS = "minecraft:weakness",
  /** 中毒 */
  POISON = "minecraft:poison",
  /** 中毒(致命) */
  FATAL_POISON = "minecraft:fatal_poison",
  /** 凋零 */
  WITHER = "minecraft:wither",
  /** 生命提升 */
  HEALTH_BOOST = "minecraft:health_boost",
  /** 伤害吸收 */
  ABSORPTION = "minecraft:absorption",
  /** 饱和 */
  SATURATION = "minecraft:saturation",
  /** 漂浮 */
  LEVITATION = "minecraft:levitation",
  /** 缓降 */
  SLOW_FALLING = "minecraft:slow_falling",
  /** 潮涌能量 */
  CONDUIT_POWER = "minecraft:conduit_power",
  /** 村庄英雄 */
  HERO_OF_THE_VILLAGE = "minecraft:hero_of_the_village",
  /** 黑暗 */
  DARKNESS = "minecraft:darkness",
}

export enum SaturationModifier {
  /** 贫瘠 */
  POOR = 0.2,
  /** 低 */
  LOW = 0.6,
  /** 正常 */
  NORMAL = 1.2,
  /** 良好 */
  GOOD = 1.6,
  /** 极佳 */
  MAX = 2.0,
  /** 超自然 */
  SUPERNATURAL = 2.4,
}
